- name: Building & Deploy Docker container
  hosts: dockerservers
  gather_facts: false
  remote_user: root
  tasks:
    - name: Stopping the Container
      docker_container:
        name: mico-container
        image: mico:latest
        state: stopped

    - name: Removing the Container
      docker_container:
        name: mico-container
        image: mico:latest
        state: absent

    - name: Removing Docker Image
      docker_image:
        name: mico:latest
        state: absent
    - name: Building Docker Image
      docker_image:
        name: mico:latest
        source: build
        build:
          path: ~/project
        state: present

    - name: Creating the Container
      docker_container:
        name: mico-container
        image: mico:latest
        ports:
          - "80:80"
        state: started